# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 강시혁
title: 서버 백엔드 엔지니어
email: zlcls456@gmail.com
website: https://kang-james.tistory.com/

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  Si-Hyeak-KANG
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: sihyukski
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
#  gtm: "GTM-0000000"
#  gtag: "UA-00000000-0"
#  google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile4.jpg
about_content: | # this will include new lines to allow paragraphs
  <b><cite>"높은 코드 이해력으로 회사에 기여하는 개발자"</cite></b>

  저의 강점인 <b>높은 코드 이해력</b>을 바탕으로

  회사 개발 환경에 빠르게 적응하고, 주도적으로 업무를 수행하여 팀에 기여합니다.

  개발 협업 프로젝트를 진행하면서 코드리뷰와 리팩토링, 기술 블로깅을 수행하였습니다.

  매번 팀의 코드와 기술을 분석한 덕분에 <b>프로그래밍 사고 역량</b>이 강화될 수 있었습니다.
  
  이 강점으로 Java1.4, Sturts1 framework 기반 복잡한 레거시 구조였던 개발환경의 회사에서
  
  4인 협업 업무에 투입되어 <b>50%에 해당하는 성과</b>를 만들었습니다.
   

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 지케스
        link: http://www.gkes.co.kr/
        link_text: gkes.co.kr
        sub_title: Java 개발자
        caption: 2023.07 - 2023.11
        description: | # this will include new lines to allow paragraphs
            - 자사 솔루션 국제화를 위한 다국어 변환 기능 개발 <small><mark>기여도 50%</mark></small>
            - 공공와이파이 데이터 연동 및 운영 <small><mark>기여도10%</mark></small>
            
      - title: 개발 도서 출판
        link: https://www.yes24.com/Product/Goods/109711067
        link_text: 도서 바로가기
        sub_title: 21인 공동 집필
        caption: 2021.12 - 2022.05
        description: | # this will include new lines to allow paragraphs
            - HTTP, HASH, MVC, CDN, SPA 용어 작성

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 다국어 변환 기능
        sub_title: (주)지케스
        caption: 2023.08 - 2023.10
        description: | # this will include new lines to allow paragraphs
          - HTTP 헤더의 Accept-Language 값을 추출 후 우선순위 적용
          - Resource Bundle를 활용하여 사용자 맞춤 다국어 제공
          - 27개 카테고리 중 약 50%에 해당하는 영역의 UI 및 서버에 다국어 적용

          <small><mark>Java1.4</mark></small> <small><mark>Struts1 Framework</mark></small> <small><mark>JSP</mark></small> <small><mark>PostgreSQL</mark></small> <small><mark>Linux</mark></small> <small><mark>SVN</mark></small> 

      - layout: left
        title: 챗봇 기반 선물하기 모바일 서비스
        # link: https://github.com/sharetreats-team/chatbot-treats-webhook
        # link_text: Github
        additional_links:
          - title:  sharetreats
            icon: fab fa-github
            url: https://github.com/sharetreats-team/chatbot-treats-webhook
        sub_title: (주)쉐어트리츠
        caption: 2023.06 - 2023.07
        description: | # this will include new lines to allow paragraphs
          1) 참여인원 : 4인 (BE 4인) <br>
          2) 역할 : <a href="https://github.com/sharetreats-team/chatbot-treats-webhook/blob/main/src/main/java/com/sharetreats/chatbot/module/service/PaymentServiceImpl.java" target='_blank'>구매 및 Point 결제 기능 개발</a>
            - Webhook을 통해 사용자 메시지에 대한 이벤트 처리 (<a href="https://developers.viber.com/docs/api/rest-bot-api/" target='_blank'>해외 대화형 앱 API 문서</a> 분석)
            - 구매 성공 시, 선물 내역 이메일 전송 기능 개발
            - 이슈 및 형상관리를 담당하여 운영, 팀 협업에 기여

          <small><mark>Java11</mark></small> <small><mark>SpringBoot</mark></small> <small><mark>JPA</mark></small> <small><mark>MySQL</mark></small> <small><mark>Redis</mark></small> <small><mark>AWS</mark></small> <small><mark>Github Action</mark></small> <small><mark>Git</mark></small> 

      - layout: left
        title: 채식주의자 식단 맞춤 쇼핑 웹 서비스
        # link: https://github.com/NOT-ERROR-056/Chaesik2s_shop_Project
        # link_text: Github
        additional_links:
          - title:  Chaesik2s_shop_project
            icon: fab fa-github
            url: https://github.com/NOT-ERROR-056/Chaesik2s_shop_Project
        sub_title: 코드스테이츠 교육
        caption: 2022.09 - 2023.04
        description: | # this will include new lines to allow paragraphs
          1) 참여인원 : 7인 (BE 4인, FE 3인) <br>
          2) 역할 : PM, 회원 인증 및 상품 도메인 구현 <br>
            - ChatGPT 기반 AI 대화형 큐레이션 기능 개발 (고객 맞춤 제품 검색 소요 시간 50% 단축)
            - <a href="https://kang-james.tistory.com/entry/SQL-%EC%B1%84%EC%8B%9D%EC%9D%B4%EB%93%A4-%ED%95%B5%EC%8B%AC-%EA%B8%B0%EB%8A%A5-%EA%B3%84%EC%B8%B5%ED%98%95-%EC%A1%B0%ED%9A%8C-%EC%BF%BC%EB%A6%AC-%EA%B5%AC%ED%98%84" target='_blank'>채식주의자 유형 데이터 계층 설계</a>로 중복 상품 제거 (채식유형별 상품 저장 비용 최대 88% 감소)
            - <a href="https://acoustic-answer-f77.notion.site/v2-f0674f0af628447e9cf16f5f02d1afe4" target='_blank'>장바구니 내의 제품 주문 기능</a> 개발 (상품 구매 후, 사용자가 직접 장바구니 내역을 삭제해야하는 번거로움 해소)
            - <a href="https://github.com/NOT-ERROR-056/Chaesik2s_shop_Project/tree/main/server/src/main/java/com/noterror/app/infra" target='_blank'>JWT 기반 회원 인증</a> 개발

          <small><mark>Java11</mark></small> <small><mark>SpringBoot</mark></small> <small><mark>JPA</mark></small> <small><mark>MySQL</mark></small> <small><mark>AWS(EC2, S3, RDS)</mark></small> <small><mark>Jira</mark></small>


      - layout: left
        title: 문화 공유 게시글 웹,앱 플랫폼
        # link: https://github.com/HowWeWork/Heritage
        # link_text: Github
        additional_links:
          - title:  Heritage
            icon: fab fa-github
            url: https://github.com/HowWeWork/Heritage_API_Server-Springboot
        caption: 2022.01 - 2022.03
        description: | # this will include new lines to allow paragraphs
          1) 참여인원 : 3인 (BE 1인, FE 1인, IOS 1인) <br>
          2) 역할 : 백엔드 서버 전체 설계 및 구현<br>
            - 무중단 배포를 위해 AWS ElasticBeanstalk 서비스 도입
            - 팀원들에게 HTTP 네트워크, REST API에 대한 지식 전달

          <small><mark>Java11</mark></small> <small><mark>SpringBoot</mark></small> <small><mark>SpringDataJPA</mark></small> <small><mark>MySQL</mark></small> <small><mark>AWS Elastic Beanstalk</mark></small> <small><mark>ajax</mark></small> <small><mark>Swift</mark></small>

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - <b>Java</b>
          - <b>Spring Boot, Spring MVC, Spring Data JPA </b>, Spring Security, Redis
          - JPA, Querydsl
          - Gradle, Maven
          - IntelliJ, Eclipse

      - title: DevOps
        description: | # this will include new lines to allow paragraphs
          - MySQL, PostgreSQL
          - AWS EC2, RDS, S3, Elastic Cache
          - Github Action

      - title: Fontend
        description: | # this will include new lines to allow paragraphs
          - JSP, Thymeleaf
          - JavaScript
          - Flutter

  - title: Education & Activities
    layout: text
    content: |
      - <b>[교육] 코드스테이츠</b>, <small><i>백엔드 코스 39기</i></small> | 2022.04 - 2022.11
      - <b>[대외] 제주더큰내일센터</b>, <small><i>탐나는인재 5기</i></small> | 2021.10 - 2022.11
      - <b>[학교] 제주대학교</b>, <small><i>메카트로닉스공학과</i></small> | 2014.03 - 2021.08
      - <b>[학교] 오현고등학교</b> | 2011.02 - 2014.02

  - title: Certificates
    layout: text
    content: |
      - <b>SQLD 자격증</b>, <small><i>한국데이터산업진흥원</i></small> | 2023.10.06

  - title: etc.
    layout: text
    content: |
      - <a href="https://github.com/BBack-BBoo-Team" target='_blank'>개발 스터디 팀 운영</a> | 알고리즘, CS 스터디 및 앱 개발
      - <a href="https://kang-james.tistory.com/entry/JPA-N1-%EB%AC%B8%EC%A0%9C%EC%99%80-Query-%EC%84%B1%EB%8A%A5-%EA%B0%9C%EC%84%A0-Fetch-Join" target='_blank'>JPA N+1 문제와 Query 성능 개선</a> | 기술 블로그 기록
      - <a href="https://youtu.be/7s14aXx1vXM?si=_EYYvE4LelHbuv3_" target='_blank'>채식 쇼핑 서비스 프로젝트 소개</a> | 협업 프로젝트 개발 과정 발표 영상
      - <a href="https://youtu.be/J7RPmACsuF8?si=YF9JppqwJVbNqhDu" target='_blank'>필드와 메서드 개념 설명</a> | (150명 동료 개발자 대상) 발표 영상

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
