# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 강시혁
title: 서버 백엔드 엔지니어
email: zlcls456@gmail.com
website: https://kang-james.tistory.com/

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  Si-Hyeak-KANG
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: sihyukski
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
###### additional_links:
###### - title: itsgoingto.be
######   icon: fas fa-globe
######   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
#  gtm: "GTM-0000000"
#  gtag: "UA-00000000-0"
#  google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile4.jpg
about_content: | # this will include new lines to allow paragraphs
  저의 강점은 '높은 코드 이해력'입니다. 취업을 준비하면서 3개의 협업 프로젝트와 알고리즘 스터디 모임을 이끌면서 역량이 발전하였습니다.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 지케스
        link: http://www.gkes.co.kr/
        link_text: gkes.co.kr
        sub_title: Java 개발자
        caption: 2023.07 - 2023.11
        quote: >
          회사 재정 악화로 인한 퇴사
        description: | # this will include new lines to allow paragraphs
            - 자사 솔루션 국제화를 위한 다국어 변환 기능 개발 <mark>기여도 50%</mark>
            - 통신사별 공공와이파이 데이터 연동 및 관리 <mark>기여도10%</mark>
            
      - title: 개발 도서 출판
        link: https://www.yes24.com/Product/Goods/109711067
        link_text: 도서 바로가기
        sub_title: 21인 공동 집필
        caption: 2021.12 - 2022.05
        quote: >
          도서명: 개발자가 되기 위해 꼭 알아야 하는 IT 용어
        description: | # this will include new lines to allow paragraphs
            - HTTP, HASH, MVC, CDN, SPA 용어 작성

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 다국어 적용
        sub_title: (주)지케스
        link: github.com/sproogen
        caption: 2023.08 - 2023.10
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          - struts 프레임워크, 자바 1.4!!!

          <mark>Java1.4</mark> <mark>Struts1 Framework</mark> <mark>JSP</mark> <mark>PostgreSQL</mark> <mark>Linux</mark>

      - layout: left
        title: 챗봇 기반 선물하기 서비스
        link: https://github.com/sharetreats-team/chatbot-treats-webhook
        link_text: Github
        sub_title: (주)쉐어트리츠
        caption: 2023.06 - 2023.07
        description: | # this will include new lines to allow paragraphs
          1) 참여인원 : 4인 (BE 4인) <br>
          2) 역할 : 구매 및 포인트 결제 기능 개발, Github 운영 <br>
            - 구매 성공 시, 선물 내역 이메일 전송 기능 구현
            - 프로젝트 기획 및 설계 과정에 전체 기여
            - 이슈 및 형상관리를 책임하여 팀 협업에 기여

          <mark>Java11</mark> <mark>SpringBoot</mark> <mark>JPA</mark> <mark>MySQL</mark> <mark>Redis</mark> <mark>AWS</mark> <mark>Github Action</mark>

      - layout: left
        title: 채식주의자 식단 맞춤 쇼핑 서비스 개발
        link: https://github.com/NOT-ERROR-056/Chaesik2s_shop_Project
        link_text: Github
        sub_title: 코드스테이츠 교육
        caption: 2022.09 - 2023.04
        description: | # this will include new lines to allow paragraphs
          1) 참여인원 : 7인 (BE 4인, FE 3인) <br>
          2) 역할 : PM, 회원 및 상품 도메인 구현 <br>
            - ChatGPT 기반 AI 대화형 큐레이션 기능 개발 (고객 맞춤 제품 검색 소요 시간 50% 단축)
            - 채식주의자 유형에 따라 데이터 구조를 계층으로 설계, 고객 맞춤 조회 쿼리 구현
            - 코드 가독성과 객체 지향 5원칙에 준수하는지 고민하며, 패키지 전체 리팩토링 진행

          <mark>Java11</mark> <mark>SpringBoot</mark> <mark>JPA</mark> <mark>MySQL</mark> <mark>AWS(EC2, S3, RDS)</mark> <mark>Jira</mark>


      - layout: left
        title: 문화 공유 플랫폼 개발
        link: https://github.com/NOT-ERROR-056/Chaesik2s_shop_Project
        link_text: Github
        sub_title: 코드스테이츠 교육
        caption: 2022.01 - 2022.03
        description: | # this will include new lines to allow paragraphs
          1) 참여인원 : 3인 (BE 1인, FE 1인, IOS 1인) <br>
          2) 역할 : 백엔드 전체 담당<br>
            - 배포에 대해서 주도적으로 학습하고, AWS Elastic Beanstalk 서비스를 통해 무중단 배포 적용
            - 팀 업무 효율 증가를 위해 Notion과 GitHub에 팀 페이지를 구축. 팀 협업에 기여
            - 팀원들에게 HTTP 네트워크, REST API에 대한 지식 전달

          <mark>Java11</mark> <mark>SpringBoot</mark> <mark>JPA</mark> <mark>MySQL</mark> <mark>AWS Elastic Beanstalk</mark>

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - <b>Java</b>
          - <b>Spring Boot, Spring MVC, Spring Data JPA </b>, Spring Security, Redis
          - JPA, Querydsl
          - Gradle, Maven
          - IntelliJ, Eclipse

      - title: DevOps
        description: | # this will include new lines to allow paragraphs
          - MySQL, PostgreSQL
          - AWS EC2, RDS, S3, Elastic Cache
          - Github Action

      - title: Fontend
        description: | # this will include new lines to allow paragraphs
          - JSP, Thymeleaf
          - JavaScript
          - Flutter

  - title: Education & Activities
    layout: text
    content: |
      - <b>[교육] 코드스테이츠</b>, <small><i>백엔드 코스 39기</i></small> | 2022.04 - 2022.11
      - <b>[대외] 제주더큰내일센터</b>, <small><i>탐나는인재 5기</i></small> | 2021.10 - 2022.11
      - <b>[학교] 제주대학교</b>, <small><i>메카트로닉스공학과</i></small> | 2014.03 - 2021.08
      - <b>[학교] 오현고등학교</b> | 2011.02 - 2014.02

  - title: Certificates
    layout: text
    content: |
      - <b>SQLD 자격증</b>, <small><i>한국데이터산업진흥원</i></small> | 2023.10.06

  - title: etc.
    layout: text
    content: |
      - <a href="https://github.com/BBack-BBoo-Team" target='_blank'>개발 스터디 팀 운영</a> | 알고리즘, CS 스터디 및 앱 개발
      - <a href="https://youtu.be/7s14aXx1vXM?si=_EYYvE4LelHbuv3_" target='_blank'>채식 쇼핑 서비스 개발 프로젝트</a> | 협업 프로젝트 발표 영상
      - <a href="https://youtu.be/J7RPmACsuF8?si=YF9JppqwJVbNqhDu" target='_blank'>필드와 메서드 개념 설명</a> | 발표 영상

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
